champs = {
 'Annie': {'pos': [0, 0], 'role': ['mid']},
 'Kayle': {'pos': [-48, 0], 'role': ['top']},
 'Xerath': {'pos': [-96, 0], 'role': ['mid']},
 'Shyvana': {'pos': [-144, 0], 'role': ['jun']},
 'Ahri': {'pos': [-192, 0], 'role': ['mid']},
 'Graves': {'pos': [-240, 0], 'role': ['top', 'jun']},
 'Fizz': {'pos': [-288, 0], 'role': ['mid']},
 'Volibear': {'pos': [-336, 0], 'role': ['top', 'jun']},
 'Rengar': {'pos': [-384, 0], 'role': ['jun']},
 'Maitre Yi': {'pos': [-432, 0], 'role': ['jun']},
 'Varus': {'pos': [0, -48], 'role': ['adc']},
 'Nautilus': {'pos': [-48, -48], 'role': ['sup']},
 'Victor': {'pos': [-96, -48], 'role': ['mid']},
 'Sejuani': {'pos': [-144, -48], 'role': ['jun']},
 'Fiora': {'pos': [-192, -48], 'role': ['top']},
 'Ziggs': {'pos': [-240, -48], 'role': ['mid', 'adc']},
 'Lulu': {'pos': [-288, -48], 'role': ['sup']},
 'Draven': {'pos': [-336, -48], 'role': ['adc']},
 'Alistar': {'pos': [-384, -48], 'role': ['sup']},
 'Hecarim': {'pos': [-432, -48], 'role': ['jun']},
 'Kha Zix': {'pos': [0, -96], 'role': ['jun']},
 'Darius': {'pos': [-48, -96], 'role': ['top']},
 'Jayce': {'pos': [-96, -96], 'role': ['top', 'mid']},
 'Lissandra': {'pos': [-144, -96], 'role': ['mid']},
 'Ryze': {'pos': [-192, -96], 'role': ['mid']},
 'Diana': {'pos': [-240, -96], 'role': ['jun', 'mid']},
 'Quinn': {'pos': [-288, -96], 'role': ['top']},
 'Syndra': {'pos': [-336, -96], 'role': ['mid']},
 'Aurelion Sol': {'pos': [-384, -96], 'role': ['mid']},
 'Sion': {'pos': [-432, -96], 'role': ['top']},
 'Kayn': {'pos': [0, -144], 'role': ['jun']},
 'Zoé': {'pos': [-48, -144], 'role': ['mid']},
 'Zyra': {'pos': [-96, -144], 'role': ['mid', 'jun', 'sup']},
 'Kai Sa': {'pos': [-144, -144], 'role': ['adc']},
 'Séraphine': {'pos': [-192, -144], 'role': ['mid', 'adc']},
 'Sivir': {'pos': [-240, -144], 'role': ['adc']},
 'Gnar': {'pos': [-288, -144], 'role': ['top']},
 'Zac': {'pos': [-336, -144], 'role': ['jun']},
 'Yasuo': {'pos': [-384, -144], 'role': ['top', 'mid']},
 'Soraka': {'pos': [-432, -144], 'role': ['sup']},
 'Vel Khoz': {'pos': [0, -192], 'role': ['mid']},
 'Taliyah': {'pos': [-48, -192], 'role': ['mid']},
 'Camille': {'pos': [-96, -192], 'role': ['top']},
 'Akshan': {'pos': [-144, -192], 'role': ['mid']},
 'Teemo': {'pos': [-192, -192], 'role': ['top']},
 'Tristana': {'pos': [-240, -192], 'role': ['top']},
 'Warwick': {'pos': [-288, -192], 'role': ['top', 'jun']},
 'Olaf': {'pos': [-336, -192], 'role': ['jun']},
 'Nunu & Willump': {'pos': [-384, -192], 'role': ['jun']},
 'BelVeth': {'pos': [-432, -192], 'role': ['jun']},
 'Braum': {'pos': [0, -240], 'role': ['sup']},
 'Jhin': {'pos': [-48, -240], 'role': ['adc']},
 'Kindred': {'pos': [-96, -240], 'role': ['jun']},
 'Miss Fortune': {'pos': [-144, -240], 'role': ['adc']},
 'Ashe': {'pos': [-192, -240], 'role': ['adc']},
 'Zeri': {'pos': [-240, -240], 'role': ['adc']},
 'Jinx': {'pos': [-288, -240], 'role': ['adc']},
 'Tahm Kench': {'pos': [-336, -240], 'role': ['top', 'sup']},
 'Tryndamere': {'pos': [-384, -240], 'role': ['top', 'jun']},
 'Briar': {'pos': [-432, -240], 'role': ['jun']}
}